/**
 * sdk-bots public entry.
 *
 * Two ways to use:
 *
 * 1. Programmatic (start the host in-process):
 *    import { startHost, SdkBotsClient } from "sdk-bots";
 *    const { port, token } = await startHost();
 *    const sdk = new SdkBotsClient({ baseUrl: `http://127.0.0.1:${port}`, token });
 *
 * 2. External (host already running as a process):
 *    import { SdkBotsClient } from "sdk-bots";
 *    const sdk = new SdkBotsClient({ baseUrl: "http://127.0.0.1:7331", token: "..." });
 */

import { randomUUID } from "node:crypto";
import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { SdkBotsClient } from "./index.js";

export { SdkBotsClient, normalizeAgentList } from "./index.js";
export type { SdkBotsClientOptions, AgentList } from "./index.js";

export interface StartHostOptions {
  /**
   * Root data directory for the host (agents, stores, gateway discovery).
   * Defaults to `~/.sdk-bots` — deliberately isolated from any Cursor/Grok Bot
   * installation, so the SDK never touches (or takes over the lock of) a real
   * `~/.cursor` data root.
   */
  dataDir?: string;
  /** Pin the gateway port. Default: the host picks a port and reports it via gateway.json. */
  port?: number;
  /** Pin the gateway auth token. Default: a fresh random token is generated by the host. */
  token?: string;
  /** How long to wait for the gateway to come up. Default 180_000 ms (cold boot can be slow). */
  startupTimeoutMs?: number;
}

export interface StartedHost {
  readonly port: number;
  readonly token?: string;
  /** Data directory the host is rooted at. */
  readonly dataDir: string;
  /** Resolved gateway baseUrl. */
  readonly baseUrl: string;
  /** Convenience client wired to this host. */
  client: SdkBotsClient;
}

/** Default SDK data root — never ~/.cursor. */
export function defaultDataDir(): string {
  return join(homedir(), ".sdk-bots");
}

/**
 * Locates the bundled loopback box exec-daemon (single-file CJS bundle built
 * into dist/box-exec-daemon by `npm run build:daemon`). Dev runs (tsx, from
 * src/sdk) and packaged runs (dist/sdk) both resolve it under dist/. Returns
 * null when absent — the host then runs without the daemon (shell/file tools
 * degraded).
 */
export function resolveBoxExecDaemonEntry(): string | null {
  const here = dirname(fileURLToPath(import.meta.url));
  const candidates = [
    join(here, "..", "box-exec-daemon", "main.cjs"), // dist/sdk -> dist/box-exec-daemon (packaged)
    join(here, "..", "..", "dist", "box-exec-daemon", "main.cjs"), // src/sdk -> dist (dev via tsx)
  ];
  for (const candidate of candidates) {
    if (existsSync(candidate)) return candidate;
  }
  return null;
}

/**
 * Loads the shared headless host composition (src/bootstrap/composition.ts)
 * and returns its boot function.
 *
 * The specifier is computed on purpose. A literal `import("../bootstrap/composition.js")`
 * would make the compiler pull the entire host runtime graph (protobuf
 * closures, tree-sitter, jimp, …) into the SDK's declaration-emit program,
 * and this package's published types should cover only the small public
 * surface below. Dev runs resolve the TypeScript source via tsx; packaged
 * runs resolve the emitted JS next to this file. The wiring itself is
 * exercised end-to-end by the smoke/e2e/integration suites, which boot a real
 * host through this exact call.
 */
async function loadHeadlessHostBoot(): Promise<() => Promise<void>> {
  const here = dirname(fileURLToPath(import.meta.url));
  const candidates = [
    "../bootstrap/composition.ts", // dev: this file is src/sdk/entry.ts (tsx)
    "../bootstrap/composition.js", // packaged: dist/sdk/entry.js
  ];
  for (const candidate of candidates) {
    if (!existsSync(resolve(here, candidate))) continue;
    const specifier: string = candidate;
    const mod = (await import(specifier)) as { startHeadlessHost: () => Promise<void> };
    return mod.startHeadlessHost;
  }
  throw new Error(
    "sdk-bots host composition module not found (expected src/bootstrap/composition.ts or dist/bootstrap/composition.js)"
  );
}

export interface GatewayDiscovery {
  port: number;
  token?: string;
}

/** Exported for unit testing. */
export async function waitForDiscovery(
  dataDir: string,
  timeoutMs: number,
  pollIntervalMs = 250
): Promise<GatewayDiscovery> {
  const path = join(dataDir, "gateway.json");
  const deadline = Date.now() + timeoutMs;
  let lastError: unknown = undefined;
  while (Date.now() < deadline) {
    try {
      const raw = await readFile(path, "utf8");
      const parsed = JSON.parse(raw);
      // Only accept a discovery record written by THIS boot: a stale
      // gateway.json from a previous run (left behind when the process exited
      // without signal-driven cleanup) would otherwise report a dead port.
      if (parsed?.port === undefined || parsed?.port <= 0) throw new Error("no port in discovery");
      if (parsed?.pid !== process.pid) throw new Error(`stale discovery from pid ${parsed?.pid}`);
      return { port: parsed.port, ...(parsed.token != null ? { token: String(parsed.token) } : {}) };
    } catch (error) {
      lastError = error; // not written yet (or stale) — keep polling
    }
    await new Promise(r => setTimeout(r, pollIntervalMs));
  }
  throw new Error(
    `sdk-bots host did not write gateway discovery at ${path} within ${timeoutMs}ms` +
    (lastError != null ? ` (last error: ${String(lastError)})` : "")
  );
}

/**
 * Starts the headless host in-process and resolves once the gateway is listening.
 *
 * Notes:
 * - The host installs its own SIGTERM/SIGINT shutdown handlers; it stops when
 *   the embedding process exits (or on SIGTERM).
 * - The recovered host reads its configuration from environment variables, so
 *   this function temporarily sets the documented ones (SAND_DATA_ROOT,
 *   SAND_HOST_PORT, SAND_GATEWAY_TOKEN, SAND_USE_EXISTING_BOX_EXEC_DAEMON).
 */
export async function startHost(options: StartHostOptions = {}): Promise<StartedHost> {
  const dataDir = resolve(options.dataDir ?? defaultDataDir());
  // The recovered host reads these environment variables lazily throughout its
  // lifetime (getSandRootDir() resolves SAND_DATA_ROOT on every call), so they
  // must stay set for the whole process - restoring them after startup would
  // split the host's data between two roots. One in-process host per process
  // is the supported shape (the host also owns process-level signal handlers).
  const envToSet: Record<string, string> = {
    // Isolate the SDK data root from any real Cursor/Grok Bot installation.
    SAND_DATA_ROOT: dataDir,
  };
  // Point the host at the bundled box exec-daemon (shell/file tool sandbox).
  // Without it, turns block forever on box readiness; when the bundle is
  // missing we degrade to the no-daemon mode instead of failing to boot.
  const daemonEntry = resolveBoxExecDaemonEntry();
  if (daemonEntry != null) {
    envToSet.SAND_BOX_EXEC_DAEMON_ENTRY = daemonEntry;
    // An explicit embedder opt-in (e.g. a second host on one machine reusing
    // the already-running daemon) wins over bundling our own; only clear the
    // flag when the embedder did not set it.
    if (process.env.SAND_USE_EXISTING_BOX_EXEC_DAEMON !== "1") {
      delete process.env.SAND_USE_EXISTING_BOX_EXEC_DAEMON;
    }
  } else {
    envToSet.SAND_USE_EXISTING_BOX_EXEC_DAEMON = "1";
  }
  if (options.port != null) envToSet.SAND_HOST_PORT = String(options.port);
  if (options.token != null) envToSet.SAND_GATEWAY_TOKEN = options.token;

  for (const [key, value] of Object.entries(envToSet)) {
    process.env[key] = value;
  }

  let discovery: GatewayDiscovery;
  {
    // Single shared wiring with the CLI bootstrap (src/bootstrap/composition.ts).
    const startHeadlessHost = await loadHeadlessHostBoot();

    // main() resolves before the discovery file is written, and resolves even
    // on the happy path only after handlers are installed — so readiness is
    // signalled by the discovery file, which is written atomically after the
    // gateway starts listening. Watch for it instead of racing on startup().
    const startup = startHeadlessHost();
    startup.catch(() => { /* fatal startup errors surface via the discovery timeout */ });

    discovery = await waitForDiscovery(dataDir, options.startupTimeoutMs ?? 180_000);
  }

  const baseUrl = `http://127.0.0.1:${discovery.port}`;
  return {
    port: discovery.port,
    ...(discovery.token != null ? { token: discovery.token } : {}),
    dataDir,
    baseUrl,
    client: new SdkBotsClient({ baseUrl, token: discovery.token }),
  };
}

/** Generates a random id useful for test agent names/nonces. */
export function randomId(): string {
  return randomUUID();
}
