import { mkdirSync, readFileSync, writeFileSync } from "node:fs"; import { dirname, join } from "node:path"; export const SAND_GROUP_FILENAME = "group.json"; export const GROUP_CONFIG_VERSION = 1;
/**
 * Group roster limits are user-configurable per group via `maxMembers` in
 * group.json. The default is 8: the 10-member-turn batch budget covers a
 * meaningful full-crew round up to ~8 @-disciplined speakers, and 玄骨-续
 * genuinely needs 美术指导/剪辑师 in the room (observed 2026-09-03: the 冷青
 * rework was blocked on a basis doc only 美术指导 could deliver, but the old
 * hard cap of 6 kept it out of the group entirely). Users may raise a group
 * up to GROUP_HARD_MAX_MEMBERS; beyond that, batch turn budgets and prompt
 * sizes degrade for everyone in the room.
 */
export const GROUP_DEFAULT_MAX_MEMBERS = 8;
export const GROUP_HARD_MAX_MEMBERS = 16;
/** Back-compat alias for the old fixed cap. */
export const GROUP_MAX_MEMBERS = GROUP_DEFAULT_MAX_MEMBERS;
export interface RemoteGroupMember { ownerAuthId: string; agentId: string; name: string; avatarDataUrl?: string } export interface SandGroupConfig { version: number; memberIds: string[]; remoteMembers?: RemoteGroupMember[]; sharedRoomId?: string; maxMembers?: number }
export function normalizeGroupMaxMembers(raw: unknown): number { const value = typeof raw === "number" ? Math.floor(raw) : Number.NaN; if (!Number.isFinite(value)) return GROUP_DEFAULT_MAX_MEMBERS; return Math.min(Math.max(value, 1), GROUP_HARD_MAX_MEMBERS); }
export function getSandGroupPath(agentDir: string): string { return join(agentDir, SAND_GROUP_FILENAME); } export function normalizeMemberIds(raw: unknown, limit: number = GROUP_DEFAULT_MAX_MEMBERS): string[] { if (!Array.isArray(raw)) return []; const seen = new Set<string>(); for (const value of raw) { if (typeof value !== "string") continue; const id = value.trim(); if (!id || seen.has(id)) continue; seen.add(id); if (seen.size >= limit) break; } return [...seen]; }
export function normalizeRemoteMembers(raw: unknown, limit: number = GROUP_DEFAULT_MAX_MEMBERS): RemoteGroupMember[] { if (!Array.isArray(raw)) return []; const seen = new Set<string>(), members: RemoteGroupMember[] = []; for (const value of raw) { if (typeof value !== "object" || value == null) continue; const candidate = value as Record<string, unknown>; if (typeof candidate.ownerAuthId !== "string" || typeof candidate.agentId !== "string") continue; const ownerAuthId = candidate.ownerAuthId.trim(), agentId = candidate.agentId.trim(), key = `${ownerAuthId}\0${agentId}`; if (!ownerAuthId || !agentId || seen.has(key)) continue; seen.add(key); members.push({ ownerAuthId, agentId, name: typeof candidate.name === "string" && candidate.name.trim() ? candidate.name.trim() : "Agent", ...(typeof candidate.avatarDataUrl === "string" && candidate.avatarDataUrl ? { avatarDataUrl: candidate.avatarDataUrl } : {}) }); if (members.length >= limit) break; } return members; }
export function readSandGroupConfig(agentDir: string): SandGroupConfig | null { let parsed: Record<string, unknown>; try { parsed = JSON.parse(readFileSync(getSandGroupPath(agentDir), "utf8")); } catch { return null; } if (typeof parsed !== "object" || parsed == null) return null; const maxMembers = normalizeGroupMaxMembers(parsed.maxMembers), memberIds = normalizeMemberIds(parsed.memberIds, maxMembers), remoteMembers = normalizeRemoteMembers(parsed.remoteMembers, maxMembers), sharedRoomId = typeof parsed.sharedRoomId === "string" && parsed.sharedRoomId.length > 0 ? parsed.sharedRoomId : undefined; if (memberIds.length === 0 && remoteMembers.length === 0 && sharedRoomId === undefined) return null; return { version: typeof parsed.version === "number" ? parsed.version : GROUP_CONFIG_VERSION, memberIds, ...(remoteMembers.length > 0 ? { remoteMembers } : {}), ...(sharedRoomId === undefined ? {} : { sharedRoomId }), maxMembers }; }
export function writeSandGroupConfig(agentDir: string, config: SandGroupConfig): void { const path = getSandGroupPath(agentDir); mkdirSync(dirname(path), { recursive: true }); const maxMembers = normalizeGroupMaxMembers(config.maxMembers); const remoteMembers = normalizeRemoteMembers(config.remoteMembers, maxMembers); writeFileSync(path, `${JSON.stringify({ version: config.version, maxMembers, memberIds: normalizeMemberIds(config.memberIds, maxMembers), ...(remoteMembers.length > 0 ? { remoteMembers } : {}), ...(config.sharedRoomId ? { sharedRoomId: config.sharedRoomId } : {}) }, null, 2)}\n`, "utf8"); } export function isSandGroupDir(agentDir: string): boolean { return readSandGroupConfig(agentDir) != null; }
